package com.acj.spa.enums;

public enum Escolaridade {
	
	FUNDAMENTAL_INCOMPLETO,
	FUNDAMENTAL_COMPLETO,
	MEDIO_COMPLETO,
	MEDIO_INCOMPLETO,
	SUPERIOR_COMPLETO,
	SUPERIOR_INCOMPLETO,
	POSGRADUACAO_INCOMPLETO,
	POSGRADUACAO_COMPLETO

}
